### ISSUE TITLE
CentroidTracker::update crash

### ISSUE THREAD

**Issue by n-mam** [prat96/Centroid-Object-Tracking#1]
I guess you probably know about this crash.. we are deleting map elements inside the range based loop resulting in invalid iterator. Do we plan to fix this anytime soon ?

**Comment by YannickLecroart** [comment]
Has it been fixed yet?

**Comment by prat96** [comment]
Hi @n-mam @YannickLecroart, apologies for the delay!
This issue has been fixed in the `fix_deletion` branch. Please checkout to this branch and test it out, I will merge to master after.

Thanks! :)

**Comment by prat96** [comment]
Merged to master.
