### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by YannickLecroart** [prat96/Centroid-Object-Tracking#3]
Hi Pratheek,

After including your library to my project, when I try to compile I get the following error messages:

    centroidtracker.cpp(91): warning C4244: 'argument': conversion from 'double' to 'const _Ty', possible loss of data
    1>        with
    1>        [
    1>            _Ty=float
    1>        ]

    centroidtracker.cpp(103): warning C4267: 'argument': conversion from 'size_t' to 'const _Ty', possible loss of data
    1>        with
    1>        [
    1>            _Ty=int
    1>        ]

    centroidtracker.cpp(166): error C3861: 'inserter': identifier not found

    centroidtracker.cpp(168): error C3861: 'inserter': identifier not found

Could you please help me out?

Thanks in advance.

Regards,

**Comment by YannickLecroart** [comment]
Pratheek,

I figured out how to solve that issue, you simply need to add  the include <iterator> on top on the centroitracker.cpp file:

    #include <iterator>

Regards,

**Comment by prat96** [comment]
Hey @YannickLecroart, thank you very much for pointing out this issue! Cheers :)
